### ISSUE TITLE
col export error

### ISSUE THREAD

**Issue by niapmomento** [Parik27/DragonFF#100]
whenever i try to export a COL file it gives me this error:
```
Python: Traceback (most recent call last):
  File "C:\Users\intel\AppData\Roaming\Blender Foundation\Blender\2.92\scripts\addons\DragonFF-master\gui\col_ot.py", line 57, in execute
    "only_selected"  : self.only_selected
  File "C:\Users\intel\AppData\Roaming\Blender Foundation\Blender\2.92\scripts\addons\DragonFF-master\ops\col_exporter.py", line 231, in export_col
    output += col_exporter.export_col(name)
  File "C:\Users\intel\AppData\Roaming\Blender Foundation\Blender\2.92\scripts\addons\DragonFF-master\ops\col_exporter.py", line 192, in export_col
    self._process_obj(obj)
  File "C:\Users\intel\AppData\Roaming\Blender Foundation\Blender\2.92\scripts\addons\DragonFF-master\ops\col_exporter.py", line 164, in _process_obj
    self.coll.mesh_faces
  File "C:\Users\intel\AppData\Roaming\Blender Foundation\Blender\2.92\scripts\addons\DragonFF-master\ops\col_exporter.py", line 55, in _process_mesh
    surface[0] = mat.dff.col_mat_index
AttributeError: 'NoneType' object has no attribute 'dff'

location: <unknown location>:-1

```
I have the most updated version of DragonFF and it still gives me this error

**Comment by Psycrow101** [comment]
Fixed by https://github.com/Parik27/DragonFF/commit/62bc7307b60b417d7c372e449c80fa3db45dcaac
