### ISSUE TITLE
error while exporting .col file

### ISSUE THREAD

**Issue by unagi2152** [Parik27/DragonFF#101]
Python: Traceback (most recent call last):
  File "C:\Users\DELL\AppData\Roaming\Blender Foundation\Blender\2.92\scripts\addons\DragonFF-master\gui\col_ot.py", line 57, in execute
    "only_selected"  : self.only_selected
  File "C:\Users\DELL\AppData\Roaming\Blender Foundation\Blender\2.92\scripts\addons\DragonFF-master\ops\col_exporter.py", line 231, in export_col
    output += col_exporter.export_col(name)
  File "C:\Users\DELL\AppData\Roaming\Blender Foundation\Blender\2.92\scripts\addons\DragonFF-master\ops\col_exporter.py", line 199, in export_col
    return col.coll(self.coll).write_memory()
  File "C:\Users\DELL\AppData\Roaming\Blender Foundation\Blender\2.92\scripts\addons\DragonFF-master\gtaLib\col.py", line 480, in write_memory
    data += self.__write_col(model)
  File "C:\Users\DELL\AppData\Roaming\Blender Foundation\Blender\2.92\scripts\addons\DragonFF-master\gtaLib\col.py", line 458, in __write_col
    data = self.__write_col_new(model)
  File "C:\Users\DELL\AppData\Roaming\Blender Foundation\Blender\2.92\scripts\addons\DragonFF-master\gtaLib\col.py", line 410, in __write_col_new
    False)
  File "C:\Users\DELL\AppData\Roaming\Blender Foundation\Blender\2.92\scripts\addons\DragonFF-master\gtaLib\col.py", line 366, in __write_block
    data += Sections.write_section(block_type, block)
  File "C:\Users\DELL\AppData\Roaming\Blender Foundation\Blender\2.92\scripts\addons\DragonFF-master\gtaLib\col.py", line 146, in write_section
    Sections.__formats[type][version], data
  File "C:\Users\DELL\AppData\Roaming\Blender Foundation\Blender\2.92\scripts\addons\DragonFF-master\gtaLib\col.py", line 136, in __write_format
    _data += pack(char, data[index])
struct.error: short format requires (-32768) <= number <= 32767

location: <unknown location>:-1

**Comment by Parik27** [comment]
Your col file has too many vertices (or the size of the col model is too large)

**Comment by unagi2152** [comment]
thank you , col model was too large
