### ISSUE TITLE
Problems Exporting gta 3 player model

### ISSUE THREAD

**Issue by Claudespeed3** [Parik27/DragonFF#104]
I was creating a custom player for gta 3 but when exporting it  i got this error:

Python: Traceback (most recent call last):
  File "C:\Users\Chasey\AppData\Roaming\Blender Foundation\Blender\2.93\scripts\addons\gta\gui.py", line 140, in execute
    dff_exporter.export_dff(
  File "C:\Users\Chasey\AppData\Roaming\Blender Foundation\Blender\2.93\scripts\addons\gta\dff_exporter.py", line 836, in export_dff
    dff_exporter.export_dff(options['file_name'])
  File "C:\Users\Chasey\AppData\Roaming\Blender Foundation\Blender\2.93\scripts\addons\gta\dff_exporter.py", line 824, in export_dff
    self.export_objects(objects)
  File "C:\Users\Chasey\AppData\Roaming\Blender Foundation\Blender\2.93\scripts\addons\gta\dff_exporter.py", line 780, in export_objects
    self.dff.write_file(self.file_name, self.version )
  File "C:\Users\Chasey\AppData\Roaming\Blender Foundation\Blender\2.93\scripts\addons\gta\dff.py", line 1954, in write_file
    content = self.write_memory(version)
  File "C:\Users\Chasey\AppData\Roaming\Blender Foundation\Blender\2.93\scripts\addons\gta\dff.py", line 1946, in write_memory
    data += self.write_clump()
  File "C:\Users\Chasey\AppData\Roaming\Blender Foundation\Blender\2.93\scripts\addons\gta\dff.py", line 1920, in write_clump
    data = Sections.write_chunk(Clump,
TypeError: write_chunk() takes 2 positional arguments but 3 were given

location: <unknown location>:-1

is there any way to fix this?

**Comment by Skyliner77** [comment]
Can you give me model? I can take a look

**Comment by vakho10** [comment]
@Skyliner77 I have the same problem with ped model. I tried to improve hooker model and got the same errors. Here's the model (with texture):
[prostitute.zip](https://github.com/Parik27/DragonFF/files/9439239/prostitute.zip)
l
