### ISSUE TITLE
Bone parent not found when importing afro.dff

### ISSUE THREAD

**Issue by gamerpaddy** [Parik27/DragonFF#109]
Try importing afro.dff from the gta3.img
object name becomes unnamed in the outliner

it throws this error:
```Error: Python script failed, check the message in the system console

... truncatedDragonFF: Bone parent not found
Traceback (most recent call last):
  File "addons\DragonFF-master\gui\dff_ot.py", line 262, in execute
    'group_materials': self.group_materials
  File "addons\DragonFF-master\ops\dff_importer.py", line 791, in import_dff
    dff_importer.import_dff(options['file_name'])
  File "addons\DragonFF-master\ops\dff_importer.py", line 764, in import_dff
    self.import_frames()
  File "addons\DragonFF-master\ops\dff_importer.py", line 666, in import_frames
    obj = bpy.data.objects.new(frame.name, mesh)
TypeError: BlendDataObjects.new(): error with argument 1, "name" -  Function.name doesn't support None from string types

location: <unknown location>:-1

location: <unknown location>:-1```

**Comment by vakho10** [comment]
@gamerpaddy I have the same error :( for ped model.

**Comment by vakho10** [comment]
@Parik27 Please help us :)
