### ISSUE TITLE
errors when exporting

### ISSUE THREAD

**Issue by mlndev** [Parik27/DragonFF#120]
when exporting me and my friends get this error message:

`Python: Traceback (most recent call last):
  File "C:\Users\Milka\AppData\Roaming\Blender Foundation\Blender\2.93\scripts\addons\DragonFF-master\gui\dff_ot.py", line 122, in execute
    dff_exporter.export_dff(
  File "C:\Users\Milka\AppData\Roaming\Blender Foundation\Blender\2.93\scripts\addons\DragonFF-master\ops\dff_exporter.py", line 840, in export_dff
    dff_exporter.export_dff(options['file_name'])
  File "C:\Users\Milka\AppData\Roaming\Blender Foundation\Blender\2.93\scripts\addons\DragonFF-master\ops\dff_exporter.py", line 828, in export_dff
    self.export_objects(objects)
  File "C:\Users\Milka\AppData\Roaming\Blender Foundation\Blender\2.93\scripts\addons\DragonFF-master\ops\dff_exporter.py", line 784, in export_objects
    self.dff.write_file(self.file_name, self.version )
  File "C:\Users\Milka\AppData\Roaming\Blender Foundation\Blender\2.93\scripts\addons\DragonFF-master\gtaLib\dff.py", line 2075, in write_file
    content = self.write_memory(version)
  File "C:\Users\Milka\AppData\Roaming\Blender Foundation\Blender\2.93\scripts\addons\DragonFF-master\gtaLib\dff.py", line 2067, in write_memory
    data += self.write_clump()
  File "C:\Users\Milka\AppData\Roaming\Blender Foundation\Blender\2.93\scripts\addons\DragonFF-master\gtaLib\dff.py", line 2047, in write_clump
    data += self.write_geometry_list()
  File "C:\Users\Milka\AppData\Roaming\Blender Foundation\Blender\2.93\scripts\addons\DragonFF-master\gtaLib\dff.py", line 1989, in write_geometry_list
    data += geometry.to_mem()
  File "C:\Users\Milka\AppData\Roaming\Blender Foundation\Blender\2.93\scripts\addons\DragonFF-master\gtaLib\dff.py", line 1337, in to_mem
    data += Sections.write(Triangle, triangle)
  File "C:\Users\Milka\AppData\Roaming\Blender Foundation\Blender\2.93\scripts\addons\DragonFF-master\gtaLib\dff.py", line 189, in write
    _data = pack(packer, *data)
struct.error: ushort format requires 0 <= number <= 0xffff

location: <unknown location>:-1`

**Comment by Parik27** [comment]
Your model contains too many vertices/polygons

**Comment by mlndev** [comment]
Thank you for your answer!

**Comment by milcsu** [comment]
I had the same issue, I deleted half of the model but it works, thanks!

**Comment by umustbeloggedintododat** [comment]
What is the polygon limit before it goes haywire?

**Comment by umustbeloggedintododat** [comment]
CRAP. i cant export my bus : (
all that work for nothing, now I feel really sad

**Comment by umustbeloggedintododat** [comment]
but I see many other modded models with way more vertices than what I have, so why is dragonff freaking out over this?

**Comment by Parik27** [comment]
You can only have 65535 vertices in a model.

**Comment by ThePortuguesePlayer** [comment]
This confuses me because I've been working with cars around 150000 verts and they export just fine...

**Comment by Parik27** [comment]
Is that spread across objects? You can have more than 65535 overall, but not in a single mesh.

**Comment by ThePortuguesePlayer** [comment]
I did one export in the past where a single object had about 37000 verts to stress test MTA once, but yeah, I meant spread across various objects. If the limit is per object, that's not so bad then. Maybe the error message should be a bit more human readable.
I wonder how a model of a bus looks like to have such vert counts in a single mesh, I am curious...

btw, Enable Lighting and Enable Modulate Material Color are still undocumented in the Wiki.

**Comment by FlorinPT** [comment]
@Parik27 Is there any way to remove this limitation?

**Comment by Parik27** [comment]
@FlorinPT No

**Comment by FlorinPT** [comment]
why no?

**Comment by FlorinPT** [comment]
I've looked through the codes and it's not impossible we need to remove a few limitations dff.py and dff_exporter.py

**Comment by FlorinPT** [comment]
If we make changes here, we can remove the limitation and I did, but after exporting, the model is corrupted.

**Comment by Parik27** [comment]
:facepalm: 

Might as well just use a different file format to remove the limitation, right?

**Comment by HalanoSiblee** [comment]
> 🤦
> 
> Might as well just use a different file format to remove the limitation, right? Like I said, you CANNOT remove this limitation. It will not be a DFF file anymore.

back when using kam's script I was able to export very high poly models
more than 65535 vertices
Give me wonder reason why you made this limitations in first place otherwise optimize the file format 
at least it should be optional.
