### ISSUE TITLE
Export problem. 

### ISSUE THREAD

**Issue by aStevennn** [Parik27/DragonFF#142]
Hi, I try to export a vehicle but I get a error code.

Python: Traceback (most recent call last):
  File "C:\Users\lenard\AppData\Roaming\Blender Foundation\Blender\3.1\scripts\addons\DragonFF-master\gui\dff_ot.py", line 122, in execute
    dff_exporter.export_dff(
  File "C:\Users\lenard\AppData\Roaming\Blender Foundation\Blender\3.1\scripts\addons\DragonFF-master\ops\dff_exporter.py", line 842, in export_dff
    dff_exporter.export_dff(options['file_name'])
  File "C:\Users\lenard\AppData\Roaming\Blender Foundation\Blender\3.1\scripts\addons\DragonFF-master\ops\dff_exporter.py", line 830, in export_dff
    self.export_objects(objects)
  File "C:\Users\lenard\AppData\Roaming\Blender Foundation\Blender\3.1\scripts\addons\DragonFF-master\ops\dff_exporter.py", line 786, in export_objects
    self.dff.write_file(self.file_name, self.version )
  File "C:\Users\lenard\AppData\Roaming\Blender Foundation\Blender\3.1\scripts\addons\DragonFF-master\gtaLib\dff.py", line 2075, in write_file
    content = self.write_memory(version)
  File "C:\Users\lenard\AppData\Roaming\Blender Foundation\Blender\3.1\scripts\addons\DragonFF-master\gtaLib\dff.py", line 2067, in write_memory
    data += self.write_clump()
  File "C:\Users\lenard\AppData\Roaming\Blender Foundation\Blender\3.1\scripts\addons\DragonFF-master\gtaLib\dff.py", line 2047, in write_clump
    data += self.write_geometry_list()
  File "C:\Users\lenard\AppData\Roaming\Blender Foundation\Blender\3.1\scripts\addons\DragonFF-master\gtaLib\dff.py", line 1989, in write_geometry_list
    data += geometry.to_mem()
  File "C:\Users\lenard\AppData\Roaming\Blender Foundation\Blender\3.1\scripts\addons\DragonFF-master\gtaLib\dff.py", line 1337, in to_mem
    data += Sections.write(Triangle, triangle)
  File "C:\Users\lenard\AppData\Roaming\Blender Foundation\Blender\3.1\scripts\addons\DragonFF-master\gtaLib\dff.py", line 189, in write
    _data = pack(packer, *data)
struct.error: ushort format requires 0 <= number <= 0xffff

location: <unknown location>:-1

**Comment by Calvin-rgb** [comment]
How many polygons does the model have?
