### ISSUE TITLE
An export error

### ISSUE THREAD

**Issue by Zackariaz** [Parik27/DragonFF#143]
yea i cant export everytime i try to export it, this appears

"Traceback (most recent call last):
  File "C:\Users\Compaq\AppData\Roaming\Blender Foundation\Blender\2.82\scripts\addons\DragonFF-master\gui\dff_ot.py", line 129, in execute
    "export_coll"    : self.export_coll
  File "C:\Users\Compaq\AppData\Roaming\Blender Foundation\Blender\2.82\scripts\addons\DragonFF-master\ops\dff_exporter.py", line 842, in export_dff
    dff_exporter.export_dff(options['file_name'])
  File "C:\Users\Compaq\AppData\Roaming\Blender Foundation\Blender\2.82\scripts\addons\DragonFF-master\ops\dff_exporter.py", line 821, in export_dff
    collection.name)
  File "C:\Users\Compaq\AppData\Roaming\Blender Foundation\Blender\2.82\scripts\addons\DragonFF-master\ops\dff_exporter.py", line 768, in export_objects
    self.export_armature(obj)                    
  File "C:\Users\Compaq\AppData\Roaming\Blender Foundation\Blender\2.82\scripts\addons\DragonFF-master\ops\dff_exporter.py", line 717, in export_armature
    bone["bone_id"],
KeyError: 'bpy_struct[key]: key "bone_id" not found'

location: <unknown location>:-1"

also i already got rid of most of the poligons i only have like 8k now lol or something like that

**Comment by Parik27** [comment]
The bone skeleton structure is invalid, you need to reuse one from an existing model

**Comment by Zackariaz** [comment]
> The bone skeleton structure is invalid, you need to reuse one from an existing model

thank you so much sir but now another error has appeared its after i try using the "parent with automatic weights" maybe i doing it wrong because i've been only using blender for like 3 days lol

**Comment by Zackariaz** [comment]
nevermind but now everytime i try seeing if smoke's model has changed the game just crashes and closes lol
