### ISSUE TITLE
so yea another export problem damn lol

### ISSUE THREAD

**Issue by Zackariaz** [Parik27/DragonFF#145]
well another one happened dkdmdsksdk and this time its me trying to ya know put the bones from another model i trying with big smoke but when i do the thing where you parent the bones with the model (i used "with automatic weights")

Traceback (most recent call last):
  File "C:\Users\Compaq\AppData\Roaming\Blender Foundation\Blender\2.82\scripts\addons\DragonFF-master\gui\dff_ot.py", line 129, in execute
    "export_coll"    : self.export_coll
  File "C:\Users\Compaq\AppData\Roaming\Blender Foundation\Blender\2.82\scripts\addons\DragonFF-master\ops\dff_exporter.py", line 842, in export_dff
    dff_exporter.export_dff(options['file_name'])
  File "C:\Users\Compaq\AppData\Roaming\Blender Foundation\Blender\2.82\scripts\addons\DragonFF-master\ops\dff_exporter.py", line 821, in export_dff
    collection.name)
  File "C:\Users\Compaq\AppData\Roaming\Blender Foundation\Blender\2.82\scripts\addons\DragonFF-master\ops\dff_exporter.py", line 761, in export_objects
    self.populate_atomic(obj)
  File "C:\Users\Compaq\AppData\Roaming\Blender Foundation\Blender\2.82\scripts\addons\DragonFF-master\ops\dff_exporter.py", line 616, in populate_atomic
    self.create_frame(obj)
  File "C:\Users\Compaq\AppData\Roaming\Blender Foundation\Blender\2.82\scripts\addons\DragonFF-master\ops\dff_exporter.py", line 326, in create_frame
    frame.parent = id_array[obj.parent.name]            
KeyError: 'Root'

location: <unknown location>:-1

**Comment by Parik27** [comment]
The parent object for the model needs to be the model and not the armature. Unparent and reparent the other way after applying auto weights.

**Comment by Zackariaz** [comment]
still doesn't work it shows the same thing

**Comment by Parik27** [comment]
Don't check Mass Export. Also you should parent in object mode instead of pose mode.

**Comment by Zackariaz** [comment]
i kinda dont know how to parent de object lol

**Comment by Zackariaz** [comment]
actually nevermind thank you it worked the only thing that is happening now is that the model turned into a titan in game lol
