### ISSUE TITLE
[Import Error] TypeError: %x format: an integer is required, not str

### ISSUE THREAD

**Issue by Greg-J** [Parik27/DragonFF#154]
I understand this is meant for GTA modding, but I am desperately trying to get the map geometry from the original Crackdown game (Xbox 360) which used Renderware as well.

I've extracted the game files and have what I believe are the appropriate files. Attempting to import any of the .dff files I have produces the following error:

```
bpy.context.space_data.system_folders_active = 1
Modules Installed (DragonFF-master) from 'D:\\Downloads\\DragonFF-master.zip' into 'C:\\Users\\Greg\\AppData\\Roaming\\Blender Foundation\\Blender\\3.2\\scripts\\addons'
bpy.context.space_data.system_folders_active = 1
Python: Traceback (most recent call last):
  File "C:\Users\Greg\AppData\Roaming\Blender Foundation\Blender\3.2\scripts\addons\DragonFF-master\gui\dff_ot.py", line 255, in execute
    importer = dff_importer.import_dff(
  File "C:\Users\Greg\AppData\Roaming\Blender Foundation\Blender\3.2\scripts\addons\DragonFF-master\ops\dff_importer.py", line 798, in import_dff
    dff_importer.import_dff(options['file_name'])
  File "C:\Users\Greg\AppData\Roaming\Blender Foundation\Blender\3.2\scripts\addons\DragonFF-master\ops\dff_importer.py", line 774, in import_dff
    self.version = "0x%05x" % self.dff.rw_version
TypeError: %x format: an integer is required, not str

```

Files for reference: https://www.dropbox.com/s/7226qky1ik66qij/fullcity.rar?dl=0

**Comment by liminal-bear** [comment]
I have the same issue too. Has a fix been found yet?
