### ISSUE TITLE
Import error keyframe_insert()() takes at most 1 positional argument 

### ISSUE THREAD

**Issue by njikmf** [Parik27/DragonFF#188]
Python: Traceback (most recent call last):
  File "\batch.py", line 61, in <module>
  File "\batch.py", line 58, in do_obj
  File "C:\Program Files\Blender Foundation\Blender 3.3\3.3\scripts\modules\bpy\ops.py", line 113, in __call__
    ret = _op_call(self.idname_py(), None, kw)
RuntimeError: Error: Python: Traceback (most recent call last):
  File "C:\Users\asdb2a\AppData\Roaming\Blender Foundation\Blender\3.3\scripts\addons\DragonFF-master\gui\dff_ot.py", line 268, in execute
    importer = dff_importer.import_dff(
  File "C:\Users\asdb2a\AppData\Roaming\Blender Foundation\Blender\3.3\scripts\addons\DragonFF-master\ops\dff_importer.py", line 813, in import_dff
    dff_importer.import_dff(options['file_name'])
  File "C:\Users\asdb2a\AppData\Roaming\Blender Foundation\Blender\3.3\scripts\addons\DragonFF-master\ops\dff_importer.py", line 784, in import_dff
    self.import_atomics()
  File "C:\Users\asdb2a\AppData\Roaming\Blender Foundation\Blender\3.3\scripts\addons\DragonFF-master\ops\dff_importer.py", line 241, in import_atomics
    self.import_materials(geom, frame, mesh)
  File "C:\Users\asdb2a\AppData\Roaming\Blender Foundation\Blender\3.3\scripts\addons\DragonFF-master\ops\dff_importer.py", line 447, in import_materials
    helper.set_uv_animation(uv_anim)
  File "C:\Users\asdb2a\AppData\Roaming\Blender Foundation\Blender\3.3\scripts\addons\DragonFF-master\ops\importer_common.py", line 189, in set_uv_animation
    mapping.inputs['Location'].keyframe_insert("default_value",
TypeError: bpy_struct.keyframe_insert()() takes at most 1 positional argument (3 given)
Location: C:\Program Files\Blender Foundation\Blender 3.3\3.3\scripts\modules\bpy\ops.py:113

**Comment by njikmf** [comment]
[h0167600.zip](https://github.com/Parik27/DragonFF/files/9830377/h0167600.zip)

**Comment by njikmf** [comment]
I found this can fix the error but I 'm not sure is it correct? Not familiar with python and blender api....

https://github.com/Parik27/DragonFF/blob/e6988985cea5d76f42a615dd61713b910ef7e5d2/ops/importer_common.py#L189
https://github.com/Parik27/DragonFF/blob/e6988985cea5d76f42a615dd61713b910ef7e5d2/ops/importer_common.py#L190

                # Could also use round here perhaps. I don't know what's better
                mapping.inputs['Location'].keyframe_insert(data_path="default_value",
                                                           index=-1, frame=frame.time * fps)
                mapping.inputs['Scale'].keyframe_insert(data_path="default_value",
                                                           index=-1, frame=frame.time * fps)

**Comment by Parik27** [comment]
Yes, that is correct. I have made the change in 05b66b068afd47a8d8f13a566a1982dc16e02cc5
