### ISSUE TITLE
Error export dff

### ISSUE THREAD

**Issue by Calvin-rgb** [Parik27/DragonFF#197]
Python: Traceback (most recent call last):
  File "C:\Users\Дмитрий\AppData\Roaming\Blender Foundation\Blender\3.3\scripts\addons\DragonFF-master\gui\dff_ot.py", line 125, in execute
    dff_exporter.export_dff(
  File "C:\Users\Дмитрий\AppData\Roaming\Blender Foundation\Blender\3.3\scripts\addons\DragonFF-master\ops\dff_exporter.py", line 985, in export_dff
    dff_exporter.export_dff(options['file_name'])
  File "C:\Users\Дмитрий\AppData\Roaming\Blender Foundation\Blender\3.3\scripts\addons\DragonFF-master\ops\dff_exporter.py", line 973, in export_dff
    self.export_objects(objects)
  File "C:\Users\Дмитрий\AppData\Roaming\Blender Foundation\Blender\3.3\scripts\addons\DragonFF-master\ops\dff_exporter.py", line 927, in export_objects
    self.dff.write_file(self.file_name, self.version )
  File "C:\Users\Дмитрий\AppData\Roaming\Blender Foundation\Blender\3.3\scripts\addons\DragonFF-master\gtaLib\dff.py", line 2314, in write_file
    content = self.write_memory(version)
  File "C:\Users\Дмитрий\AppData\Roaming\Blender Foundation\Blender\3.3\scripts\addons\DragonFF-master\gtaLib\dff.py", line 2306, in write_memory
    data += self.write_clump()
  File "C:\Users\Дмитрий\AppData\Roaming\Blender Foundation\Blender\3.3\scripts\addons\DragonFF-master\gtaLib\dff.py", line 2286, in write_clump
    data += self.write_geometry_list()
  File "C:\Users\Дмитрий\AppData\Roaming\Blender Foundation\Blender\3.3\scripts\addons\DragonFF-master\gtaLib\dff.py", line 2228, in write_geometry_list
    data += geometry.to_mem()
  File "C:\Users\Дмитрий\AppData\Roaming\Blender Foundation\Blender\3.3\scripts\addons\DragonFF-master\gtaLib\dff.py", line 1590, in to_mem
    data += self.material_list_to_mem()
  File "C:\Users\Дмитрий\AppData\Roaming\Blender Foundation\Blender\3.3\scripts\addons\DragonFF-master\gtaLib\dff.py", line 1484, in material_list_to_mem
    data += material.to_mem()
  File "C:\Users\Дмитрий\AppData\Roaming\Blender Foundation\Blender\3.3\scripts\addons\DragonFF-master\gtaLib\dff.py", line 449, in to_mem
    data += Sections.write(RGBA, self.color)
  File "C:\Users\Дмитрий\AppData\Roaming\Blender Foundation\Blender\3.3\scripts\addons\DragonFF-master\gtaLib\dff.py", line 191, in write
    _data = pack(packer, *data)
struct.error: ubyte format requires 0 <= number <= 255

What is the problem? Before that, the export worked fine, replaced one material with another and an error began to come out

**Comment by Parik27** [comment]
Include the .blend file with the issue. It's not possible for me to debug the issue with just the stack trace.

**Comment by Calvin-rgb** [comment]
@Parik27 
[car-garage.zip](https://github.com/Parik27/DragonFF/files/9982767/car-garage.zip)

**Comment by Parik27** [comment]
The material (cr_sg_route_albedo) has colours RGB value = (590, 590, 590).

![image](https://user-images.githubusercontent.com/12731160/201152212-34bf8c0b-395f-4759-9bd7-42320054f421.png)

**Comment by Calvin-rgb** [comment]
Thank you for your help!
