### ISSUE TITLE
Issue when trying to export

### ISSUE THREAD

**Issue by marki123** [Parik27/DragonFF#203]
Python: Traceback (most recent call last):
  File "C:\Users\markg\AppData\Roaming\Blender Foundation\Blender\2.91\scripts\addons\DragonFF-master\gui\dff_ot.py", line 132, in execute
    "export_coll"    : self.export_coll
  File "C:\Users\markg\AppData\Roaming\Blender Foundation\Blender\2.91\scripts\addons\DragonFF-master\ops\dff_exporter.py", line 985, in export_dff
    dff_exporter.export_dff(options['file_name'])
  File "C:\Users\markg\AppData\Roaming\Blender Foundation\Blender\2.91\scripts\addons\DragonFF-master\ops\dff_exporter.py", line 973, in export_dff
    self.export_objects(objects)
  File "C:\Users\markg\AppData\Roaming\Blender Foundation\Blender\2.91\scripts\addons\DragonFF-master\ops\dff_exporter.py", line 927, in export_objects
    self.dff.write_file(self.file_name, self.version )
  File "C:\Users\markg\AppData\Roaming\Blender Foundation\Blender\2.91\scripts\addons\DragonFF-master\gtaLib\dff.py", line 2313, in write_file
    with open(filename, mode='wb') as file:
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\markg\\Desktop\\ezaz\\'

location: <unknown location>:-1

**Comment by Parik27** [comment]
You didn't specify a file-name.
