### ISSUE TITLE
Import Traceback Error

### ISSUE THREAD

**Issue by KatakMelompat69** [Parik27/DragonFF#240]
so i want to import some gta sa mod from youtube but error like this
Python: Traceback (most recent call last):
  File "C:\Users\Admin\AppData\Roaming\Blender Foundation\Blender\3.6\scripts\addons\DragonFF-master\gui\dff_ot.py", line 268, in execute
    importer = dff_importer.import_dff(
  File "C:\Users\Admin\AppData\Roaming\Blender Foundation\Blender\3.6\scripts\addons\DragonFF-master\ops\dff_importer.py", line 824, in import_dff
    dff_importer.import_dff(options['file_name'])
  File "C:\Users\Admin\AppData\Roaming\Blender Foundation\Blender\3.6\scripts\addons\DragonFF-master\ops\dff_importer.py", line 795, in import_dff
    self.import_atomics()
  File "C:\Users\Admin\AppData\Roaming\Blender Foundation\Blender\3.6\scripts\addons\DragonFF-master\ops\dff_importer.py", line 241, in import_atomics
    self.import_materials(geom, frame, mesh)
  File "C:\Users\Admin\AppData\Roaming\Blender Foundation\Blender\3.6\scripts\addons\DragonFF-master\ops\dff_importer.py", line 431, in import_materials
    helper.set_specular_material(plugin)
  File "C:\Users\Admin\AppData\Roaming\Blender Foundation\Blender\3.6\scripts\addons\DragonFF-master\ops\importer_common.py", line 158, in set_specular_material
    self.material.dff.specular_texture = plugin.texture.decode('ascii')
UnicodeDecodeError: 'ascii' codec can't decode byte 0xff in position 16: ordinal not in range(128)

How to fix this???

**Comment by Psycrow101** [comment]
Have you solved this issue?
