### ISSUE TITLE
Problems of Exporting Cars to DFF

### ISSUE THREAD

**Issue by johnnie-br** [Parik27/DragonFF#270]
When I export a DFF I got an error:
![image](https://github.com/Parik27/DragonFF/assets/133685928/7dda4011-6f1d-4f03-97b0-3654d3dd8df8)
![image](https://github.com/Parik27/DragonFF/assets/133685928/8466b7b3-59e5-4f07-a022-0265d6aa94a5)
```Python: Traceback (most recent call last):
  File "C:\Users\jonat\AppData\Roaming\Blender Foundation\Blender\4.0\scripts\addons\DragonFF-master\gui\dff_ot.py", line 134, in execute
    dff_exporter.export_dff(
  File "C:\Users\jonat\AppData\Roaming\Blender Foundation\Blender\4.0\scripts\addons\DragonFF-master\ops\dff_exporter.py", line 995, in export_dff
    dff_exporter.export_dff(options['file_name'])
  File "C:\Users\jonat\AppData\Roaming\Blender Foundation\Blender\4.0\scripts\addons\DragonFF-master\ops\dff_exporter.py", line 982, in export_dff
    self.export_objects(objects)
  File "C:\Users\jonat\AppData\Roaming\Blender Foundation\Blender\4.0\scripts\addons\DragonFF-master\ops\dff_exporter.py", line 922, in export_objects
    mem = export_col({
  File "C:\Users\jonat\AppData\Roaming\Blender Foundation\Blender\4.0\scripts\addons\DragonFF-master\ops\col_exporter.py", line 240, in export_col
    return col_exporter.export_col(options['file_name'])
  File "C:\Users\jonat\AppData\Roaming\Blender Foundation\Blender\4.0\scripts\addons\DragonFF-master\ops\col_exporter.py", line 192, in export_col
    self._process_obj(obj)
  File "C:\Users\jonat\AppData\Roaming\Blender Foundation\Blender\4.0\scripts\addons\DragonFF-master\ops\col_exporter.py", line 162, in _process_obj
    self._process_mesh(obj,
  File "C:\Users\jonat\AppData\Roaming\Blender Foundation\Blender\4.0\scripts\addons\DragonFF-master\ops\col_exporter.py", line 55, in _process_mesh
    surface[0] = mat.dff.col_mat_index
AttributeError: 'NoneType' object has no attribute 'dff'
```
![image](https://github.com/Parik27/DragonFF/assets/133685928/81dd1324-6560-4f96-be83-4439ad1046fd)
Apparently all options are OK, so I don't know what it could be

**Comment by Parik27** [comment]
There seems to be a material in one of the collision models that was not created with DragonFF installed.

**Comment by johnnie-br** [comment]
> There seems to be a material in one of the collision models that was not created with DragonFF installed.

Hmm, thanks for the help, but, now I got this: 
![image](https://github.com/Parik27/DragonFF/assets/133685928/5e163052-7cc2-4ac6-b7e8-f2eb3ccc6fd5)
Here is the log:
[gta_sa.exe_2024-01-19_00-39-41.log](https://github.com/Parik27/DragonFF/files/13983885/gta_sa.exe_2024-01-19_00-39-41.log)

**Comment by johnnie-br** [comment]
Could the problem be resolved in the same way as indicated in the message on the screen? but with dragonff, or is there another way?
