### ISSUE TITLE
Import error

### ISSUE THREAD

**Issue by alphaoctacube** [Parik27/DragonFF#276]
I'm getting this error when I'm importing a certain DFF file:

struct.error: unpack_from requires a buffer of at least 18683434 bytes for unpacking 4 bytes at offset 18683430 (actual buffer size is 18557108)

What shall I do to fix this?

**Comment by alphaoctacube** [comment]
@Parik27 it would be very much appreciated if you could respond to this quickly

**Comment by alphaoctacube** [comment]
[Uploading gr86.zip…]()
Here's the DFF file in case if you want to check it

**Comment by Parik27** [comment]
The link does not work and your error is incomplete (does not contain a stack trace).

**Comment by alphaoctacube** [comment]
Python: Traceback (most recent call last):
  File "C:\Users\▉▉▉▉\AppData\Roaming\Blender Foundation\Blender\3.6\scripts\addons\DragonFF-master\gui\dff_ot.py", line 278, in execute
    importer = dff_importer.import_dff(
  File "C:\Users\▉▉▉▉\AppData\Roaming\Blender Foundation\Blender\3.6\scripts\addons\DragonFF-master\ops\dff_importer.py", line 824, in import_dff
    dff_importer.import_dff(options['file_name'])
  File "C:\Users\▉▉▉▉\AppData\Roaming\Blender Foundation\Blender\3.6\scripts\addons\DragonFF-master\ops\dff_importer.py", line 785, in import_dff
    self.dff.load_file(file_name)
  File "C:\Users\▉▉▉▉\AppData\Roaming\Blender Foundation\Blender\3.6\scripts\addons\DragonFF-master\gtaLib\dff.py", line 2196, in load_file
    self.load_memory(content)
  File "C:\Users\▉▉▉▉\AppData\Roaming\Blender Foundation\Blender\3.6\scripts\addons\DragonFF-master\gtaLib\dff.py", line 2171, in load_memory
    self.read_clump(chunk)
  File "C:\Users\▉▉▉▉\AppData\Roaming\Blender Foundation\Blender\3.6\scripts\addons\DragonFF-master\gtaLib\dff.py", line 2125, in read_clump
    self.read_geometry_list(chunk)
  File "C:\Users\▉▉▉▉\AppData\Roaming\Blender Foundation\Blender\3.6\scripts\addons\DragonFF-master\gtaLib\dff.py", line 2030, in read_geometry_list
    self.read_material_list(chunk)
  File "C:\Users\▉▉▉▉\AppData\Roaming\Blender Foundation\Blender\3.6\scripts\addons\DragonFF-master\gtaLib\dff.py", line 1946, in read_material_list
    self.read_matfx(material, chunk)
  File "C:\Users\▉▉▉▉\AppData\Roaming\Blender Foundation\Blender\3.6\scripts\addons\DragonFF-master\gtaLib\dff.py", line 1846, in read_matfx
    effect_type = unpack_from("<I", self.data, self._read(4))[0]
struct.error: unpack_from requires a buffer of at least 18683434 bytes for unpacking 4 bytes at offset 18683430 (actual buffer size is 18557108)

**Comment by alphaoctacube** [comment]
there's the stack trace, and here's the link to the DFF file:
https://drive.google.com/file/d/1g5rNwRJgRHyzsNRqxNcfbbtlWNu4fkhv/view?usp=sharing
