### ISSUE TITLE
issue when importing

### ISSUE THREAD

**Issue by sovietgu** [Parik27/DragonFF#287]
trying to import "duneride.dff" in blender give me that:

Python: Traceback (most recent call last):
  File "C:\Users\hp\AppData\Roaming\Blender Foundation\Blender\3.3\scripts\addons\DragonFF-master\gui\dff_ot.py", line 278, in execute
    importer = dff_importer.import_dff(
  File "C:\Users\hp\AppData\Roaming\Blender Foundation\Blender\3.3\scripts\addons\DragonFF-master\ops\dff_importer.py", line 827, in import_dff
    dff_importer.import_dff(options['file_name'])
  File "C:\Users\hp\AppData\Roaming\Blender Foundation\Blender\3.3\scripts\addons\DragonFF-master\ops\dff_importer.py", line 788, in import_dff
    self.dff.load_file(file_name)
  File "C:\Users\hp\AppData\Roaming\Blender Foundation\Blender\3.3\scripts\addons\DragonFF-master\gtaLib\dff.py", line 2214, in load_file
    self.load_memory(content)
  File "C:\Users\hp\AppData\Roaming\Blender Foundation\Blender\3.3\scripts\addons\DragonFF-master\gtaLib\dff.py", line 2189, in load_memory
    self.read_clump(chunk)
  File "C:\Users\hp\AppData\Roaming\Blender Foundation\Blender\3.3\scripts\addons\DragonFF-master\gtaLib\dff.py", line 2139, in read_clump
    self.read_frame_list(chunk)
  File "C:\Users\hp\AppData\Roaming\Blender Foundation\Blender\3.3\scripts\addons\DragonFF-master\gtaLib\dff.py", line 1685, in read_frame_list
    if self.frame_list[i].name is None:
IndexError: list index out of range

**Comment by Psycrow101** [comment]
@sovietgu duneride.dff is imported without errors for me. Can you send your dff file?
