### ISSUE TITLE
Problem When Exporting Col File

### ISSUE THREAD

**Issue by jonatasfsj** [Parik27/DragonFF#295]
When I want to export Col file, I Got problem:
```Python: Traceback (most recent call last):
  File "C:\Users\jonat\AppData\Roaming\Blender Foundation\Blender\4.0\scripts\addons\DragonFF-master\gui\col_ot.py", line 50, in execute
    col_exporter.export_col(
  File "C:\Users\jonat\AppData\Roaming\Blender Foundation\Blender\4.0\scripts\addons\DragonFF-master\ops\col_exporter.py", line 231, in export_col
    output += col_exporter.export_col(name)
  File "C:\Users\jonat\AppData\Roaming\Blender Foundation\Blender\4.0\scripts\addons\DragonFF-master\ops\col_exporter.py", line 199, in export_col
    return col.coll(self.coll).write_memory()
  File "C:\Users\jonat\AppData\Roaming\Blender Foundation\Blender\4.0\scripts\addons\DragonFF-master\gtaLib\col.py", line 480, in write_memory
    data += self.__write_col(model)
  File "C:\Users\jonat\AppData\Roaming\Blender Foundation\Blender\4.0\scripts\addons\DragonFF-master\gtaLib\col.py", line 458, in __write_col
    data = self.__write_col_new(model)
  File "C:\Users\jonat\AppData\Roaming\Blender Foundation\Blender\4.0\scripts\addons\DragonFF-master\gtaLib\col.py", line 408, in __write_col_new
    data += self.__write_block(TVertex,
  File "C:\Users\jonat\AppData\Roaming\Blender Foundation\Blender\4.0\scripts\addons\DragonFF-master\gtaLib\col.py", line 366, in __write_block
    data += Sections.write_section(block_type, block)
  File "C:\Users\jonat\AppData\Roaming\Blender Foundation\Blender\4.0\scripts\addons\DragonFF-master\gtaLib\col.py", line 145, in write_section
    return Sections.__write_format(
  File "C:\Users\jonat\AppData\Roaming\Blender Foundation\Blender\4.0\scripts\addons\DragonFF-master\gtaLib\col.py", line 136, in __write_format
    _data += pack(char, data[index])
struct.error: short format requires (-32768) <= number <= 32767
```
I have no idea to solve this

**Comment by jonatasfsj** [comment]
![image](https://github.com/Parik27/DragonFF/assets/164420919/27d4930c-828c-484d-a43d-a3cecf29ae68)
![image](https://github.com/Parik27/DragonFF/assets/164420919/2b4635e2-53e0-4f08-a5b8-71116c243180)
![image](https://github.com/Parik27/DragonFF/assets/164420919/0aa46464-7c76-47d6-a896-8b790315211e)

**Comment by Parik27** [comment]
Your collision file might be too large in dimensions. There's a limit on their size. Try scaling it down or splitting it into multiple objects.

**Comment by jonatasfsj** [comment]
Okay, thank you very much
