### ISSUE TITLE
Don't work export collision

### ISSUE THREAD

**Issue by Calvin-rgb** [Parik27/DragonFF#297]
Python: Traceback (most recent call last):
  File "C:\Users\Dimx\AppData\Roaming\Blender Foundation\Blender\4.1\scripts\addons\DragonFF-master\gui\col_ot.py", line 50, in execute
    col_exporter.export_col(
  File "C:\Users\Dimx\AppData\Roaming\Blender Foundation\Blender\4.1\scripts\addons\DragonFF-master\ops\col_exporter.py", line 231, in export_col
    output += col_exporter.export_col(name)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Dimx\AppData\Roaming\Blender Foundation\Blender\4.1\scripts\addons\DragonFF-master\ops\col_exporter.py", line 199, in export_col
    return col.coll(self.coll).write_memory()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Dimx\AppData\Roaming\Blender Foundation\Blender\4.1\scripts\addons\DragonFF-master\gtaLib\col.py", line 480, in write_memory
    data += self.__write_col(model)
            ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Dimx\AppData\Roaming\Blender Foundation\Blender\4.1\scripts\addons\DragonFF-master\gtaLib\col.py", line 468, in __write_col
    model.model_name.encode("ascii"),
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
UnicodeEncodeError: 'ascii' codec can't encode characters in position 0-8: ordinal not in range(128)

Version blender: 4.1
Plugin DragonFF last update install
Vertices in export col model: 283

**Comment by Psycrow101** [comment]
@Calvin-rgb can you attach the .blend project?

**Comment by Calvin-rgb** [comment]
> @Calvin-rgb can you attach the .blend project?

[test.zip](https://github.com/user-attachments/files/15810896/test.zip)

**Comment by Psycrow101** [comment]
Is this the right file? I'm getting another error when exporting. In the attached project, the mesh size is too large and the coordinates of some vertices do not fit into the format restrictions. To solve this, you can reduce the scale of the mesh or move it closer to the center

**Comment by Calvin-rgb** [comment]
> Is this the right file? I'm getting another error when exporting it. In the attached project, the mesh scale is too large and the coordinates of some vertices are out of bounds. To solve this, you can reduce the scale of the mesh or move it closer to the center

Strange, this is the first time I’ve heard about the grid scale being exceeded, there’s no such thing in 3ds max

**Comment by Parik27** [comment]
Sure there is. It's a limitation of the col format.
