### ISSUE TITLE
Import error

### ISSUE THREAD

**Issue by bingusgaming490** [Parik27/DragonFF#306]
I imported a dff file from the Madagascar game (PC) into Blender 3.6.5 and it gives this error

Python: Traceback (most recent call last):
  File "C:\Users\USER\AppData\Roaming\Blender Foundation\Blender\3.6\scripts\addons\DragonFF-master\gui\dff_ot.py", line 278, in execute
    importer = dff_importer.import_dff(
  File "C:\Users\USER\AppData\Roaming\Blender Foundation\Blender\3.6\scripts\addons\DragonFF-master\ops\dff_importer.py", line 824, in import_dff
    dff_importer.import_dff(options['file_name'])
  File "C:\Users\USER\AppData\Roaming\Blender Foundation\Blender\3.6\scripts\addons\DragonFF-master\ops\dff_importer.py", line 796, in import_dff
    self.import_frames()
  File "C:\Users\USER\AppData\Roaming\Blender Foundation\Blender\3.6\scripts\addons\DragonFF-master\ops\dff_importer.py", line 715, in import_frames
    obj.parent = self.objects[frame.parent]
IndexError: list index out of range

I noticed there's 2 meshes imported when this plugin usually imports all parts in one combined mesh and that may have something to do with it.

![Screenshot 2024-06-05 182944](https://github.com/Parik27/DragonFF/assets/120013221/896b245d-6bd3-4dd2-89d6-a296bfe01c72)
[Dff file](https://drive.google.com/file/d/1q-OFrCouQXJ7Ejrog1PysBefNcsxUZSs/view?usp=sharing)

**Comment by Psycrow101** [comment]
Try this branch https://github.com/Psycrow101/DragonFF/tree/multi-mesh
