### ISSUE TITLE
Exporting DFF with a custom version of 3.2.0.0 (according to GTA III's player.dff) results a "Sections.write_chunk()" error

### ISSUE THREAD

**Issue by jaigitrep159** [Parik27/DragonFF#311]
```python
Traceback (most recent call last):
  File "C:\Users\USER\AppData\Roaming\Blender Foundation\Blender\3.6\scripts\addons\DragonFF-master\gui\dff_ot.py", line 141, in execute
    dff_exporter.export_dff(
  File "C:\Users\USER\AppData\Roaming\Blender Foundation\Blender\3.6\scripts\addons\DragonFF-master\ops\dff_exporter.py", line 1003, in export_dff
    dff_exporter.export_dff(options['file_name'])
  File "C:\Users\USER\AppData\Roaming\Blender Foundation\Blender\3.6\scripts\addons\DragonFF-master\ops\dff_exporter.py", line 989, in export_dff
    self.export_objects(objects)
  File "C:\Users\USER\AppData\Roaming\Blender Foundation\Blender\3.6\scripts\addons\DragonFF-master\ops\dff_exporter.py", line 943, in export_objects
    self.dff.write_file(self.file_name, self.version )
  File "C:\Users\USER\AppData\Roaming\Blender Foundation\Blender\3.6\scripts\addons\DragonFF-master\gtaLib\dff.py", line 2421, in write_file
    content = self.write_memory(version)
  File "C:\Users\USER\AppData\Roaming\Blender Foundation\Blender\3.6\scripts\addons\DragonFF-master\gtaLib\dff.py", line 2413, in write_memory
    data += self.write_clump()
  File "C:\Users\USER\AppData\Roaming\Blender Foundation\Blender\3.6\scripts\addons\DragonFF-master\gtaLib\dff.py", line 2387, in write_clump
    data = Sections.write_chunk(Clump,
TypeError: Sections.write_chunk() takes 2 positional arguments but 3 were given
```

# Reproduce:
1. Make a new scene
2. Delete everything **except the default cube**
3. Export parameters:
Export Collision: **True**
Export Frame Names: **True**
Version Export: **Custom**
Custom Version: **3.2.0.0**
4. Click Export DFF and caused a **_"Sections.write_chunk()"_** error

Tested in Blender 3.6.8 LTS, using the latest DragonFF build (native-plg update)

**Comment by Psycrow101** [comment]
This should fix it

https://github.com/Parik27/DragonFF/commit/baa449d0d409e797145a506cc039ca428302a3ea

**Comment by jaigitrep159** [comment]
![image](https://github.com/Parik27/DragonFF/assets/76834328/5d03be6d-fa92-4bae-ad01-a918f3bba062)
![image](https://github.com/Parik27/DragonFF/assets/76834328/cc901c16-3b94-4b64-9115-d46cede9bbef)
Thank you for this small fix.
