### ISSUE TITLE
error while exporting

### ISSUE THREAD

**Issue by ripkoondieeq** [Parik27/DragonFF#318]
**basically idk if its on my end but i made my own flash for gta sa aaaand this is what i get in return when i try to export** 

Python: Traceback (most recent call last):
  File "C:\Users\pc\AppData\Roaming\Blender Foundation\Blender\4.1\scripts\addons\DragonFF-master\gui\dff_ot.py", line 125, in execute
    "0x%c%c%c0%c" % (self.custom_version[0],
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\pc\AppData\Roaming\Blender Foundation\Blender\4.1\scripts\addons\DragonFF-master\ops\dff_exporter.py", line 903, in export_dff
    frame.bone_data = bone_data
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\jasiek\AppData\Roaming\Blender Foundation\Blender\4.1\scripts\addons\DragonFF-master\ops\dff_exporter.py", line 891, in export_dff
    continue
^^^^^^^^^^^^^
  File "C:\Users\pc\AppData\Roaming\Blender Foundation\Blender\4.1\scripts\addons\DragonFF-master\ops\dff_exporter.py", line 823, in export_objects
    parent = obj.parent
            ^^^^^^^^^^^^
  File "C:\Users\pc\AppData\Roaming\Blender Foundation\Blender\4.1\scripts\addons\DragonFF-master\ops\dff_exporter.py", line 667, in populate_atomic
    # Only upto 4 vertices per group are supported
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\pc\AppData\Roaming\Blender Foundation\Blender\4.1\scripts\addons\DragonFF-master\ops\dff_exporter.py", line 537, in populate_geometry_with_mesh_data
    # bones
^^^^^^^^^^^^
AttributeError: 'Mesh' object has no attribute 'calc_normals_split'

**Comment by Psycrow101** [comment]
Looks like you are using too old version of DragonFF

**Comment by ripkoondieeq** [comment]
> Looks like you are using too old version of DragonFF

strange i reinstalled it minutes before posting that, i will go check tho

**Comment by ripkoondieeq** [comment]
ok yea it works
