### ISSUE TITLE
Error importing DFF model

### ISSUE THREAD

**Issue by korolevkh** [Parik27/DragonFF#324]
Python: Traceback (most recent call last):
  File "C:\Users\Роман\AppData\Roaming\Blender Foundation\Blender\4.1\scripts\addons\DragonFF-master\gtaLib\dff.py", line 2301, in load_file
    self.load_memory(content)
  File "C:\Users\Роман\AppData\Roaming\Blender Foundation\Blender\4.1\scripts\addons\DragonFF-master\gtaLib\dff.py", line 2280, in load_memory
    self.read_uv_anim_dict()
  File "C:\Users\Роман\AppData\Roaming\Blender Foundation\Blender\4.1\scripts\addons\DragonFF-master\gtaLib\dff.py", line 2257, in read_uv_anim_dict
    for i in range(num_anims):
                   ^^^^^^^^^
UnboundLocalError: cannot access local variable 'num_anims' where it is not associated with a value

I'm trying to import a skin from GTA SA
[barselona.zip](https://github.com/user-attachments/files/16112898/barselona.zip)

**Comment by Psycrow101** [comment]
Solved by https://github.com/Parik27/DragonFF/commit/574509d8d9a05e1d1fc085a9f5d7d9bc6ad82177
