### ISSUE TITLE
List index out of range when importing Renderware 3 DFF model

### ISSUE THREAD

**Issue by hejsanbajs** [Parik27/DragonFF#325]
Python: Traceback (most recent call last):
  File "C:\Users\wrenq\AppData\Roaming\Blender Foundation\Blender\3.3\scripts\addons\DragonFF-master\gui\dff_ot.py", line 286, in execute
    importer = dff_importer.import_dff(
  File "C:\Users\wrenq\AppData\Roaming\Blender Foundation\Blender\3.3\scripts\addons\DragonFF-master\ops\dff_importer.py", line 839, in import_dff
    dff_importer.import_dff(options['file_name'])
  File "C:\Users\wrenq\AppData\Roaming\Blender Foundation\Blender\3.3\scripts\addons\DragonFF-master\ops\dff_importer.py", line 810, in import_dff
    self.import_atomics()
  File "C:\Users\wrenq\AppData\Roaming\Blender Foundation\Blender\3.3\scripts\addons\DragonFF-master\ops\dff_importer.py", line 116, in import_atomics
    geom = self.dff.geometry_list[atomic.geometry]
IndexError: list index out of range

[DLL file](https://drive.google.com/file/d/1JG9l5sJB9RE6J1IMDYeX9hOqDOMrpYR5/)

**Comment by Psycrow101** [comment]
After the latest update this model can be imported without errors, but it will not have any rigging. I suspect the necessary data is stored in the "Bone PLG" section, but I don't know how to parse it

![image](https://github.com/user-attachments/assets/14134858-a273-4ee7-8aef-2630197d7d1b)

**Comment by Psycrow101** [comment]
The "Bone PLG" section contains a set of vertex groups data:
```
uint start_vertex
uint num_vertices
uint bone_id
```

For parsing:
```python
GeomBone = namedtuple("GeomBone", "start_vertex num_vertices bone_id") # "<3I"

def read_bone_plg(self, parent_chunk, geometry):
    chunk_end = self.pos + parent_chunk.size

    geom_bones = []
    while self.pos < chunk_end:
        bone = Sections.read(GeomBone, self.data, self._read(12))
        if bone.num_vertices > 0:
            geom_bones.append(bone)

    geometry.extensions['bones'] = geom_bones
```

Frame's bone_id is stored in the "Animation PLG" section.

![image](https://github.com/user-attachments/assets/72a3272d-1200-4b24-8017-78ecd65019b6)
