### ISSUE TITLE
Exporting Error.

### ISSUE THREAD

**Issue by JagleW** [Parik27/DragonFF#45]
Hello, when I am trying to export my model using DragonFF, error showed bellow is showing to me. It happenes when I export both DFF and COL.
![image](https://user-images.githubusercontent.com/44727277/87467314-0e522280-c618-11ea-94db-5a5b2a2278cb.png)
I'm also attaching all needed project files.
[Project Files.zip](https://github.com/Parik27/DragonFF/files/4920859/Project.Files.zip)

**Comment by Parik27** [comment]
This was fixed in 53de04f0eed70c6eca41d545ae2b480655fb542a, on March 22, do you have a version older than that by any chance?

**Comment by JagleW** [comment]
I've been using 0.11 from tags tab, because newer versions from 'code' tab (dragonff-master) do not work, when I'm installing it, blender shows that I have installed it successfully but when I'm searching for it to enable it I don't see it. Also addons folder does not include it, even though i have installed it.
I am not only person, who have this problem. I seen few more a.e in Discord.
![image](https://user-images.githubusercontent.com/44727277/87546785-66396980-c6aa-11ea-9208-01f4a6eb03d0.png)

**Comment by Parik27** [comment]
You should try the latest version from master then, you're gonna have to re-zip it since GitHub puts it into a folder of its own.

What you have to do is - extract the archive, and create an archive of just the gta folder. You should then be able to install it directly. Alternatively you can extract the gta folder in the plugins folder of your Blender installation manually.

**Comment by ArrivakCZ** [comment]
Dobrý den mám tady toten problém a nevím jak to opravit ??? můžete mi prosím poradit co stím ...
Traceback (most recent call last):
  File "C:\Users\lenovo\AppData\Roaming\Blender Foundation\Blender\2.83\scripts\addons\gta\gui.py", line 147, in execute
    "export_coll"    : self.export_coll
  File "C:\Users\lenovo\AppData\Roaming\Blender Foundation\Blender\2.83\scripts\addons\gta\dff_exporter.py", line 836, in export_dff
    dff_exporter.export_dff(options['file_name'])
  File "C:\Users\lenovo\AppData\Roaming\Blender Foundation\Blender\2.83\scripts\addons\gta\dff_exporter.py", line 824, in export_dff
    self.export_objects(objects)
  File "C:\Users\lenovo\AppData\Roaming\Blender Foundation\Blender\2.83\scripts\addons\gta\dff_exporter.py", line 773, in export_objects
    'collection' : self.collection
  File "C:\Users\lenovo\AppData\Roaming\Blender Foundation\Blender\2.83\scripts\addons\gta\col_exporter.py", line 210, in export_col
    return col_exporter.export_col(options['file_name'])
  File "C:\Users\lenovo\AppData\Roaming\Blender Foundation\Blender\2.83\scripts\addons\gta\col_exporter.py", line 198, in export_col
    return col.coll(self.coll).write_memory()
  File "C:\Users\lenovo\AppData\Roaming\Blender Foundation\Blender\2.83\scripts\addons\gta\col.py", line 481, in write_memory
    data += self.__write_col(model)
  File "C:\Users\lenovo\AppData\Roaming\Blender Foundation\Blender\2.83\scripts\addons\gta\col.py", line 459, in __write_col
    data = self.__write_col_new(model)
  File "C:\Users\lenovo\AppData\Roaming\Blender Foundation\Blender\2.83\scripts\addons\gta\col.py", line 399, in __write_col_new
    data += self.__write_block(TSphere, model.spheres, False)
  File "C:\Users\lenovo\AppData\Roaming\Blender Foundation\Blender\2.83\scripts\addons\gta\col.py", line 366, in __write_block
    data += Sections.write_section(block_type, block)
  File "C:\Users\lenovo\AppData\Roaming\Blender Foundation\Blender\2.83\scripts\addons\gta\col.py", line 146, in write_section
    Sections.__formats[type][version], data
  File "C:\Users\lenovo\AppData\Roaming\Blender Foundation\Blender\2.83\scripts\addons\gta\col.py", line 133, in __write_format
    _data += Sections.write_section(TSurface, data[index])
  File "C:\Users\lenovo\AppData\Roaming\Blender Foundation\Blender\2.83\scripts\addons\gta\col.py", line 146, in write_section
    Sections.__formats[type][version], data
  File "C:\Users\lenovo\AppData\Roaming\Blender Foundation\Blender\2.83\scripts\addons\gta\col.py", line 136, in __write_format
    _data += pack(char, data[index])
struct.error: required argument is not an integer

location: <unknown location>:-1

Blender 2.83 , DragonFF nejnovější co jsem našel tady

**Comment by JagleW** [comment]
You're kinda lucky that I am half Polish and half Czech. Im gonna translate it for Dragon.

Hello, I have an problem and I dont know how to fix it. I would like to ask you for help. 

(logs)

Blender 2.83, DragonFF, newest version that is available to download.

**Comment by Psycrow101** [comment]
Is this issue still relevant?

**Comment by dascaluxenon** [comment]
![image](https://github.com/user-attachments/assets/5b3e6311-e732-4e8c-bcaa-94535c18b84d)
freeze when i want export model .dff 
No every model getting freeze,but some models getting crash without explication and that is unexpected 
How to resolve that ? 
I tryied to resize verticals and others for compression but not work.
