### ISSUE TITLE
Question.

### ISSUE THREAD

**Issue by NeXt2k19** [Parik27/DragonFF#52]
Hello,
I have a problem in Export to .dff
Console Log:
Traceback (most recent call last):
  File "C:\Users\lukas\AppData\Roaming\Blender Foundation\Blender\2.83\scripts\addons\gta\gui.py", line 147, in execute
    "export_coll"    : self.export_coll
  File "C:\Users\lukas\AppData\Roaming\Blender Foundation\Blender\2.83\scripts\addons\gta\dff_exporter.py", line 835, in export_dff
    dff_exporter.export_dff(options['file_name'])
  File "C:\Users\lukas\AppData\Roaming\Blender Foundation\Blender\2.83\scripts\addons\gta\dff_exporter.py", line 823, in export_dff
    self.export_objects(objects)
  File "C:\Users\lukas\AppData\Roaming\Blender Foundation\Blender\2.83\scripts\addons\gta\dff_exporter.py", line 779, in export_objects
    self.dff.write_file(self.file_name, self.version )
  File "C:\Users\lukas\AppData\Roaming\Blender Foundation\Blender\2.83\scripts\addons\gta\dff.py", line 1955, in write_file
    content = self.write_memory(version)
  File "C:\Users\lukas\AppData\Roaming\Blender Foundation\Blender\2.83\scripts\addons\gta\dff.py", line 1947, in write_memory
    data += self.write_clump()
  File "C:\Users\lukas\AppData\Roaming\Blender Foundation\Blender\2.83\scripts\addons\gta\dff.py", line 1927, in write_clump
    data += self.write_geometry_list()
  File "C:\Users\lukas\AppData\Roaming\Blender Foundation\Blender\2.83\scripts\addons\gta\dff.py", line 1869, in write_geometry_list
    data += geometry.to_mem()
  File "C:\Users\lukas\AppData\Roaming\Blender Foundation\Blender\2.83\scripts\addons\gta\dff.py", line 1232, in to_mem
    data += Sections.write(Triangle, triangle)
  File "C:\Users\lukas\AppData\Roaming\Blender Foundation\Blender\2.83\scripts\addons\gta\dff.py", line 179, in write
    _data = pack(packer, *data)
struct.error: ushort format requires 0 <= number <= 0xffff

location: <unknown location>:-1

**Comment by Parik27** [comment]
You have too many vertices in your model.
