### ISSUE TITLE
uv animation

### ISSUE THREAD

**Issue by Pateeesz** [Parik27/DragonFF#59]
I can't import uv animated objects.

```Traceback (most recent call last):
  File "C:\Users\Felhasználó\AppData\Roaming\Blender Foundation\Blender\2.90\scripts\addons\DragonFF-master\gui\dff_ot.py", line 262, in execute
    'group_materials': self.group_materials
  File "C:\Users\Felhasználó\AppData\Roaming\Blender Foundation\Blender\2.90\scripts\addons\DragonFF-master\ops\dff_importer.py", line 790, in import_dff
    dff_importer.import_dff(options['file_name'])
  File "C:\Users\Felhasználó\AppData\Roaming\Blender Foundation\Blender\2.90\scripts\addons\DragonFF-master\ops\dff_importer.py", line 762, in import_dff
    self.import_atomics()
  File "C:\Users\Felhasználó\AppData\Roaming\Blender Foundation\Blender\2.90\scripts\addons\DragonFF-master\ops\dff_importer.py", line 235, in import_atomics
    self.import_materials(geom, frame, mesh)
  File "C:\Users\Felhasználó\AppData\Roaming\Blender Foundation\Blender\2.90\scripts\addons\DragonFF-master\ops\dff_importer.py", line 440, in import_materials
    helper.set_uv_animation(uv_anim)
  File "C:\Users\Felhasználó\AppData\Roaming\Blender Foundation\Blender\2.90\scripts\addons\DragonFF-master\ops\importer_common.py", line 176, in set_uv_animation
    mapping.translation = frame.uv[-2:] + [0]
ValueError: bpy_struct: item.attr = val: sequences of dimension 0 should contain 2 items, not 3

location: <unknown location>:-1

**Comment by Parik27** [comment]
Thanks for reporting it - I'll look into it.

**Comment by Parik27** [comment]
Should be fixed in the latest version

**Comment by Pateeesz** [comment]
I'm using 2.90.1

```Traceback (most recent call last):
  File "C:\Users\Felhasználó\AppData\Roaming\Blender Foundation\Blender\2.90\scripts\addons\DragonFF-master\gui\dff_ot.py", line 262, in execute
    'group_materials': self.group_materials
  File "C:\Users\Felhasználó\AppData\Roaming\Blender Foundation\Blender\2.90\scripts\addons\DragonFF-master\ops\dff_importer.py", line 790, in import_dff
    dff_importer.import_dff(options['file_name'])
  File "C:\Users\Felhasználó\AppData\Roaming\Blender Foundation\Blender\2.90\scripts\addons\DragonFF-master\ops\dff_importer.py", line 762, in import_dff
    self.import_atomics()
  File "C:\Users\Felhasználó\AppData\Roaming\Blender Foundation\Blender\2.90\scripts\addons\DragonFF-master\ops\dff_importer.py", line 235, in import_atomics
    self.import_materials(geom, frame, mesh)
  File "C:\Users\Felhasználó\AppData\Roaming\Blender Foundation\Blender\2.90\scripts\addons\DragonFF-master\ops\dff_importer.py", line 440, in import_materials
    helper.set_uv_animation(uv_anim)
  File "C:\Users\Felhasználó\AppData\Roaming\Blender Foundation\Blender\2.90\scripts\addons\DragonFF-master\ops\importer_common.py", line 176, in set_uv_animation
    mapping.input_template['Location'].default_value = frame.uv[-2:] + [0]
AttributeError: 'ShaderNodeMapping' object has no attribute 'translation'

location: <unknown location>:-1

**Comment by ThePortuguesePlayer** [comment]
Could we get some documentation on how the UV animation works?

**Comment by Parik27** [comment]
Doesn't look like the plugin refreshed completely. I'd suggest restarting Blender or deleting the Python cache. I tested it on 2.90.1 as well.

UV Animation works by splitting an image into different sections that change every frame. In Blender they're added by adding a Mapping node to the Vector input for the image. You then add keyframes to the location and scale to configure which part of the image the UV map will use on that frame.

![](https://i.imgur.com/RNJASaO.png)
![](https://i.imgur.com/nsA143R.png)

Here's an example of UV Animation. The model and textures are from https://gtaforums.com/topic/854355-animatedac/

**Comment by Pateeesz** [comment]
SMH, blender restart fixed it. Thank you.

**Comment by ThePortuguesePlayer** [comment]
Thank you!

**Comment by Dante-1337** [comment]
Hello, i been at it for a few hours now but i cant figure this out for the sake of me. Even tho i have the interpolation set to constant in blender (in order to jump from one frame to another), it still is linear in game, resulting in sliding thru the texture instead of jumping from one frame to the other. What am i missing?

**Comment by Parik27** [comment]
> Hello, i been at it for a few hours now but i cant figure this out for the sake of me. Even tho i have the interpolation set to constant in blender (in order to jump from one frame to another), it still is linear in game, resulting in sliding thru the texture instead of jumping from one frame to the other. What am i missing?

Create a new issue
