### ISSUE TITLE
Can't import map section

### ISSUE THREAD

**Issue by nifanfa** [Parik27/DragonFF#67]
bpy.context.space_data.context = 'VIEW_LAYER'
bpy.context.space_data.context = 'SCENE'
bpy.context.scene.dff.game_version_dropdown = 'VC'
bpy.context.scene.dff.map_sections = 'DATA\MAPS\oceandrv\oceandrv.IPL'
bpy.context.space_data.recent_folders_active = 1
bpy.context.space_data.system_bookmarks_active = 1
Python: Traceback (most recent call last):
  File "C:\Users\Fanfa Ni\AppData\Roaming\Blender Foundation\Blender\2.91\scripts\addons\gta\map_importer.py", line 132, in modal
    self.import_object(context)
  File "C:\Users\Fanfa Ni\AppData\Roaming\Blender Foundation\Blender\2.91\scripts\addons\gta\map_importer.py", line 108, in import_object
    'group_materials': True,
  File "C:\Users\Fanfa Ni\AppData\Roaming\Blender Foundation\Blender\2.91\scripts\addons\gta\dff_importer.py", line 780, in import_dff
    dff_importer.import_dff(options['file_name'])
  File "C:\Users\Fanfa Ni\AppData\Roaming\Blender Foundation\Blender\2.91\scripts\addons\gta\dff_importer.py", line 753, in import_dff
    self.import_frames()
  File "C:\Users\Fanfa Ni\AppData\Roaming\Blender Foundation\Blender\2.91\scripts\addons\gta\dff_importer.py", line 693, in import_frames
    obj.parent = self.objects[frame.parent]
IndexError: list index out of range

location: <unknown location>:-1

![QQ截图20201228073134](https://user-images.githubusercontent.com/54205437/103181705-ebbe7800-48de-11eb-8c04-2e5fa8c87d56.png)

**Comment by nifanfa** [comment]
![QQ截图20201228073605](https://user-images.githubusercontent.com/54205437/103181738-5c659480-48df-11eb-82d0-4ea32df31cde.png)  
As for the game. i downloaded it from steam

**Comment by nifanfa** [comment]
The version of blender is 2.91
