### ISSUE TITLE
Some mods' parts being imported as a corrupted ball mesh

### ISSUE THREAD

**Issue by umustbeloggedintododat** [Parik27/DragonFF#68]
I don't really know how to explain it, but some parts get corrupted on import on mods.
(SA)
![GLITCH](https://user-images.githubusercontent.com/54049600/103470681-22631b00-4d43-11eb-8f95-d1afae6f3a70.png)

**Comment by umustbeloggedintododat** [comment]
And here's the error:
`Python: Traceback (most recent call last):
  File "C:\Users\squid\AppData\Roaming\Blender Foundation\Blender\2.91\scripts\addons\gta\gui.py", line 282, in execute
    'group_materials': self.group_materials
  File "C:\Users\squid\AppData\Roaming\Blender Foundation\Blender\2.91\scripts\addons\gta\dff_importer.py", line 780, in import_dff
    dff_importer.import_dff(options['file_name'])
  File "C:\Users\squid\AppData\Roaming\Blender Foundation\Blender\2.91\scripts\addons\gta\dff_importer.py", line 760, in import_dff
    col = import_col_mem(collision, os.path.basename(file_name), False)
  File "C:\Users\squid\AppData\Roaming\Blender Foundation\Blender\2.91\scripts\addons\gta\col_importer.py", line 195, in import_col_mem
    return col.add_to_scene(collection_prefix, link)
  File "C:\Users\squid\AppData\Roaming\Blender Foundation\Blender\2.91\scripts\addons\gta\col_importer.py", line 179, in add_to_scene
    True)
  File "C:\Users\squid\AppData\Roaming\Blender Foundation\Blender\2.91\scripts\addons\gta\col_importer.py", line 153, in __add_mesh
    self.__add_mesh_mats(obj, materials)
  File "C:\Users\squid\AppData\Roaming\Blender Foundation\Blender\2.91\scripts\addons\gta\col_importer.py", line 101, in __add_mesh_mats
    mat = bpy.data.materials.new(name)
TypeError: BlendDataMaterials.new(): error with argument 1, "name" -  Function.name expected a string type, not list

location: <unknown location>:-1`

**Comment by Parik27** [comment]
Would you be able share the dff file you're trying to import to make it easier to debug?

**Comment by umustbeloggedintododat** [comment]
Yes, sure,
https://www.mediafire.com/file/zjpbwsbcp8hu57q/landstal.dff/file
It happens with other dffs too.

**Comment by Parik27** [comment]
![image](https://user-images.githubusercontent.com/12731160/103483725-4a1fb500-4e0f-11eb-8eb9-62e6d1576433.png)
Loads perfectly fine for me. 

Make sure you're loading them using the File > Import > DragonFF DFF (.dff) option.

**Comment by Parik27** [comment]
Also make sure you use the latest version of DragonFF - https://github.com/Parik27/DragonFF/archive/master.zip

**Comment by umustbeloggedintododat** [comment]
Alright.

**Comment by umustbeloggedintododat** [comment]
oh, didn't know there is a new version of dragonff, I was downloading from the releases
