### ISSUE TITLE
Export Error

### ISSUE THREAD

**Issue by 13Stewartc** [Parik27/DragonFF#75]
Car exported fine a few months ago (last time I used this addon) but now I get an export error. Not sure what the issue is.

```Python: Traceback (most recent call last):
  File "C:\Users\MYUSER\AppData\Roaming\Blender Foundation\Blender\2.91\scripts\addons\gta\gui.py", line 147, in execute
    "export_coll"    : self.export_coll
  File "C:\Users\MYUSER\AppData\Roaming\Blender Foundation\Blender\2.91\scripts\addons\gta\dff_exporter.py", line 836, in export_dff
    dff_exporter.export_dff(options['file_name'])
  File "C:\Users\MYUSER\AppData\Roaming\Blender Foundation\Blender\2.91\scripts\addons\gta\dff_exporter.py", line 824, in export_dff
    self.export_objects(objects)
  File "C:\Users\MYUSER\AppData\Roaming\Blender Foundation\Blender\2.91\scripts\addons\gta\dff_exporter.py", line 773, in export_objects
    'collection' : self.collection
  File "C:\Users\MYUSER\AppData\Roaming\Blender Foundation\Blender\2.91\scripts\addons\gta\col_exporter.py", line 210, in export_col
    return col_exporter.export_col(options['file_name'])
  File "C:\Users\MYUSER\AppData\Roaming\Blender Foundation\Blender\2.91\scripts\addons\gta\col_exporter.py", line 191, in export_col
    self._process_obj(obj)
  File "C:\Users\MYUSER\AppData\Roaming\Blender Foundation\Blender\2.91\scripts\addons\gta\col_exporter.py", line 158, in _process_obj
    self.coll.shadow_faces
  File "C:\Users\MYUSER\AppData\Roaming\Blender Foundation\Blender\2.91\scripts\addons\gta\col_exporter.py", line 55, in _process_mesh
    surface[0] = mat.dff.col_mat_index
AttributeError: 'NoneType' object has no attribute 'dff'

location: <unknown location>:-1
```

A few hierarchy images that may or may not be helpful: 

https://prnt.sc/105sex8
https://prnt.sc/105sfe1

**Comment by Parik27** [comment]
You should update to the latest version of DragonFF by downloading a zip of the entire GitHub repository. That should fix the issue.  If not, it seems to be related to collision materials.

**Comment by 13Stewartc** [comment]
Thank you, installed latest version and double checked the collision materials! :) Its all working now. Do you have further plans for updates etc for this addon ?

**Comment by Parik27** [comment]
Glad to hear that. I do have future plans for update, particularly support for txd archives, img support, animation support and to extend support for dff extensions in the future. I've been busy with other projects/real life at the moment, so I haven't been able to work on it as much as I'd like to in the past few months/last year. I do plan to eventually get to it though.
