### ISSUE TITLE
KeyError (Export Error)

### ISSUE THREAD

**Issue by R0X0RE0** [Parik27/DragonFF#95]
I tried to make my own player skin by importing a Blaziken model into my project space, decimating the faces, and rigging the model to the imported player armature and got this error

```
Traceback (most recent call last):
  File "C:\Users\Dylan Hawley\AppData\Roaming\Blender Foundation\Blender\2.82\scripts\addons\DragonFF-master\gui\dff_ot.py", line 129, in execute
    "export_coll"    : self.export_coll
  File "C:\Users\Dylan Hawley\AppData\Roaming\Blender Foundation\Blender\2.82\scripts\addons\DragonFF-master\ops\dff_exporter.py", line 840, in export_dff
    dff_exporter.export_dff(options['file_name'])
  File "C:\Users\Dylan Hawley\AppData\Roaming\Blender Foundation\Blender\2.82\scripts\addons\DragonFF-master\ops\dff_exporter.py", line 828, in export_dff
    self.export_objects(objects)
  File "C:\Users\Dylan Hawley\AppData\Roaming\Blender Foundation\Blender\2.82\scripts\addons\DragonFF-master\ops\dff_exporter.py", line 759, in export_objects
    self.populate_atomic(obj)
  File "C:\Users\Dylan Hawley\AppData\Roaming\Blender Foundation\Blender\2.82\scripts\addons\DragonFF-master\ops\dff_exporter.py", line 616, in populate_atomic
    self.create_frame(obj)
  File "C:\Users\Dylan Hawley\AppData\Roaming\Blender Foundation\Blender\2.82\scripts\addons\DragonFF-master\ops\dff_exporter.py", line 326, in create_frame
    frame.parent = id_array[obj.parent.name]            
KeyError: 'Normal'

location: <unknown location>:-1

```

also here is a screenshot if this helps
![blaziken](https://user-images.githubusercontent.com/44986343/120581066-31d0b800-c3f8-11eb-8769-e3f5e04e925c.png)

**Comment by R0X0RE0** [comment]
Turns out it was a parenting problem. The object is supposed to be the parent, not the armature
