### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by Skyliner77** [Parik27/DragonFF#98]
Just trying to export the model, others exported just fine, this one struggles for some reason.
Export type: collision object, format .dff

Traceback (most recent call last):
  File "C:\Users\Skyliner\AppData\Roaming\Blender Foundation\Blender\2.90\scripts\addons\DragonFF-master\gui\dff_ot.py", line 129, in execute
    "export_coll"    : self.export_coll
  File "C:\Users\Skyliner\AppData\Roaming\Blender Foundation\Blender\2.90\scripts\addons\DragonFF-master\ops\dff_exporter.py", line 840, in export_dff
    dff_exporter.export_dff(options['file_name'])
  File "C:\Users\Skyliner\AppData\Roaming\Blender Foundation\Blender\2.90\scripts\addons\DragonFF-master\ops\dff_exporter.py", line 828, in export_dff
    self.export_objects(objects)
  File "C:\Users\Skyliner\AppData\Roaming\Blender Foundation\Blender\2.90\scripts\addons\DragonFF-master\ops\dff_exporter.py", line 777, in export_objects
    'mass_export'   : False
  File "C:\Users\Skyliner\AppData\Roaming\Blender Foundation\Blender\2.90\scripts\addons\DragonFF-master\ops\col_exporter.py", line 240, in export_col
    return col_exporter.export_col(options['file_name'])
  File "C:\Users\Skyliner\AppData\Roaming\Blender Foundation\Blender\2.90\scripts\addons\DragonFF-master\ops\col_exporter.py", line 199, in export_col
    return col.coll(self.coll).write_memory()
  File "C:\Users\Skyliner\AppData\Roaming\Blender Foundation\Blender\2.90\scripts\addons\DragonFF-master\gtaLib\col.py", line 480, in write_memory
    data += self.__write_col(model)
  File "C:\Users\Skyliner\AppData\Roaming\Blender Foundation\Blender\2.90\scripts\addons\DragonFF-master\gtaLib\col.py", line 458, in __write_col
    data = self.__write_col_new(model)
  File "C:\Users\Skyliner\AppData\Roaming\Blender Foundation\Blender\2.90\scripts\addons\DragonFF-master\gtaLib\col.py", line 410, in __write_col_new
    False)
  File "C:\Users\Skyliner\AppData\Roaming\Blender Foundation\Blender\2.90\scripts\addons\DragonFF-master\gtaLib\col.py", line 366, in __write_block
    data += Sections.write_section(block_type, block)
  File "C:\Users\Skyliner\AppData\Roaming\Blender Foundation\Blender\2.90\scripts\addons\DragonFF-master\gtaLib\col.py", line 146, in write_section
    Sections.__formats[type][version], data
  File "C:\Users\Skyliner\AppData\Roaming\Blender Foundation\Blender\2.90\scripts\addons\DragonFF-master\gtaLib\col.py", line 136, in __write_format
    _data += pack(char, data[index])
struct.error: short format requires (-32768) <= number <= 32767

location: <unknown location>:-1

**Comment by Skyliner77** [comment]
Solved: decreased model size, for some reason when I tried it first time it didn't work.
